### ISSUE TITLE
Uncaught exception after deleting a PageTemplate

### ISSUE THREAD

**Issue by Dynamo6** [Laravel-Backpack/PageManager#38] opened 2017-05-15 14:58 UTC
Hi guys, this is only a minor issue but I thought I'd flag it anyway. 

Steps to reproduce:

1. create a custom PageTemplate (e.g. "contact") defined within the trait at app\PageTemplates.php
2. create a new page, assign the "contact" template and save
3. delete the custom PageTemplate from app\PageTemplates.php
4. attempt to edit the page created in step 2

You receive "BadMethodCallException in Controller.php line 82: Method [contact] does not exist."

**Comment by lloy0076** [comment] 2017-05-30 01:18
== Response

There's a few things here:

1. The issue is reproducible
2. The issue is somewhat understandable
    - Ideally, developers would not be able to remove templates that are in use
3. Current behaviour is, imho, a *bug*:
    - Whilst the situation **is** *exceptional*, now that it's been pointed out, we **should** catch it
4. There is more we can do but see below.

=== Minimum Viable Fix

- Add documentation indicating that developers who delete the configuration for in-use templates risk the system just breaking **and** leave things as they are

=== Possible Ideal Fix

- Refactor the whole system so that the trait no longer needs to even exist and the field definitions are read from a database or some storage with a really nice UI

*Note:* This would be a **stupendously** large amount of work.

=== Initial Fix

- Intercept the code and if the method does *not* exist, throw a nicer error

=== Other Notes

Another low hanging cherry would be to go through *all* defined pages and complain about any where the template configuration is missing or cannot be found!

**Comment by tabacitu** [comment] 2017-07-05 13:53
Damn... I agree with you guys, this is a problem I've also faced. 

I'm afraid @lloy0076 's solution (to provide a better error message) is all we can do, though. We have no way of preventing the developer from deleting the method, if it's being used by a DB entry. And since this is a "developer error", I believe the better error message should suffice...

BTW @lloy0076 , I think "_stupendously_" is a good word for the amount of work :-))

Closing the issue, but feel free to comment if you feel a better solution exists.

Cheers!

**Closed by tabacitu** 2017-07-05 13:53 UTC
Labels: bug, working on it
