### ISSUE TITLE
None of the views in the given array exist

### ISSUE THREAD

**Issue by madviking** [Laravel-Backpack/PageManager#123] opened 2022-02-12 10:29 UTC
# Bug report

### What I did:
Installed Backpack + PageManager on an existing project. Had to add PageTemplates.php manually. Backpack works and I can see a page listing. I added a view file under resources/pages/normal.blade.php. 

### What I expected to happen:
Being able to add a page

### What happened:
When I click "Add page", I get this error:
"None of the views in the given array exist"

Here is the stack trace:
https://flareapp.io/share/xPQ8LXgm

### Backpack, Laravel, PHP, DB version:
Backpack: 5.0.5
Laravel: 8.79.0
PHP: 8.0.8
MySQL: 5.1.0

**Comment by tabacitu** [comment] 2022-02-12 12:58
Hey @madviking ,

While investigation your problem I found and fixed something else (see https://github.com/Laravel-Backpack/CRUD/pull/4186 ) but I don't think that will fix your problem per-se.

If you're using `view_namespace` in fields, however... you should benefit from https://github.com/Laravel-Backpack/CRUD/pull/4184/files which I also just merged.

Bottom line:
- please run `composer update backpack/crud` to get to 5.0.6;
- if the problem is still there, please copy-paste your `addField()` definition, so we get a better idea of what's going on; from what I understand, your `resources/pages/normal.blade.php` is a field, correct? If so... I see it's not in the `resources/views` directory - so the path entered might not be correct;

Cheers!

**Comment by tabacitu** [comment] 2022-02-12 13:21
Ah... there you go. Now I understand. If you're using `backpack/crud` without `backpack/pro`, please use the `summernote` field instead. That one is free. 

You can see a comparison of the FREE vs PAID features here - https://backpackforlaravel.com/docs/5.x/features-free-vs-paid and more specifically of the fields here - https://backpackforlaravel.com/docs/5.x/crud-fields

But this brings up a good point. This message is NOT clear enough. It should say "_This is a PRO field. Use a FREE field instead, or purchase and use backpack/pro_". We've avoided using this because it would bloat up `backpack/crud` with the information of "what's inside backpack/pro" but... seeing your issue and imagining the frustration... I don't think we can avoid that... 

I think it'll be better to bloat up the codebase a bit... but provide a good Developer Experience. If the message had said that... you'd have zero questions, right?

**Comment by tabacitu** [comment] 2022-02-15 09:14
Thanks @madviking - I've just added a different issue in order to make Backpack throw better error messages in this use case - https://github.com/Laravel-Backpack/CRUD/issues/4196

**Closed by tabacitu** 2022-02-15 09:14 UTC
