### ISSUE TITLE
Cannot view created page

### ISSUE THREAD

**Issue by vishalbhide** [Laravel-Backpack/PageManager#2] opened 2016-06-10 12:27 UTC
Hi,

Using the PageManager, I created a simple page with a slug as 'about'. I am unable to view this page when I click on Preview (redirects to url myapp/about), I receive a 404 error.

I tried various URLs to view the page. I receive a 404 error on the below urls
myapp/about
myapp/page/about
myapp/admin/about

I receive a 403 error on the below paths for this url - myapp/admin/page/about

**Comment by tabacitu** [comment] 2016-06-13 15:26
Hi!

The initial idea was to let every developer code his own front-side logic for PageManager, but after quite a few requests I've decided we'll also include that - at least as an example.

Here's what the front-end will include, you can use this code as your own:

__routes.php:__
```php
/** CATCH-ALL ROUTE for Backpack/PageManager - needs to be at the end of your routes.php file  **/
Route::get('{page}/{subs?}', ['uses' => 'PageController@index'])
    ->where(['page' => '^((?!admin).)*$', 'subs' => '.*']);
```

__app/Http/Controllers/PageController.php:__
```php
<?php

namespace App\Http\Controllers;

use Backpack\PageManager\app\Models\Page;

class PageController extends Controller
{
	public function index($slug_or_id)
	{
		$page = Page::findBySlugOrId($slug_or_id);

		if (!$page)
		{
			abort(404, 'Please go back to our <a href="'.url('').'">homepage</a>.');
		}

		$this->data['title'] = $page->title;
		$this->data['page'] = $page->withFakes();

		return view('pages.'.$page->template, $this->data);
	}
}

```

Of course, you will need to have your page templates in resources/views/pages, with the same name you used in your PageTemplates functions.

Hope this helps!

**Comment by vishalbhide** [comment] 2016-06-14 07:38
Thank you! This does help. Great work on the overall framework! I am closing this issue.

**Comment by tabacitu** [comment] 2016-06-14 16:20
Glad that works for you! I'm going to leave the issue open until I push the PageController and route, so we don't forget. Cheers!

**Comment by mpixelz** [comment] 2016-09-12 04:03
Hi,
Im new to laravel and ive been playing with backpack demo to setup a simple application.. but im not able to use this page manager even on the demo installation..
ive added the routes.php code as suggested above as well as the pagescontroller.php 
but now the 404 error have been replaced with another error... can anyone point it to a guide where this issue is resolved?
error im getting now: 
`BadMethodCallException in Builder.php line 2405:
Call to undefined method Illuminate\Database\Query\Builder::findBySlugOrId()`
i didnt get the part about the templates? any sample we can work with to start off?
thanks.
much appreciated.

**Comment by vishalbhide** [comment] 2016-09-12 05:11
It seems that you might not have correctly added the sluggable package. Please review the setup instructions for the PageManager package - https://github.com/Laravel-Backpack/PageManager and ensure that the Cviebrock\EloquentSluggable\ServiceProvider::class is is in your config/app.php. (I don't know if the demo project loads this provider or not) Hopefully that should resolve your issue

**Comment by mpixelz** [comment] 2016-09-12 05:40
i just checked it was not there.. but i have added that now and then i did composer update to make sure everything was up to date..
so now i have updated everything and the serviceprovider is also there but the issue is still there.

**Comment by vishalbhide** [comment] 2016-09-12 06:27
Then no idea, I can't help you further.

**Comment by tabacitu** [comment] 2016-09-12 09:41
Hi @mpixelz , @vishalbhide ,

Found it! Apparently:
- v4 of eloquent-sluggable has a different trait for fetching items (```SluggableScopeHelpers``` - why, I don't know). The Page model was not using it;
- v4 of eloquent-sluggable no longer provides the ```getBySlugOrId()``` method (why? again, beats me);

Version 1.1.1 of Backpack\PageManager fixes all these issues. So running a ```composer update``` should definitely fix it. In addition, your PageController needs this small change:
```diff
<?php

namespace App\Http\Controllers;

use Backpack\PageManager\app\Models\Page;

class PageController extends Controller
{
-    public function index($slug_or_id)
+    public function index($slug)
    {
-        $page = Page::findBySlugOrId($slug_or_id);
+        $page = Page::findBySlug($slug);

        if (!$page)
        {
            abort(404, 'Please go back to our <a href="'.url('').'">homepage</a>.');
        }

        $this->data['title'] = $page->title;
        $this->data['page'] = $page->withFakes();

        return view('pages.'.$page->template, $this->data);
    }
}
```

Cheers!

P.S. I'll go ahead and close this issue so we don't clog the section. Feel free to open it again if you encounter problems or comment if you have follow-ups.

**Closed by tabacitu** 2016-09-12 09:41 UTC
Labels: bug

**Comment by andreich1980** [comment] 2017-01-10 07:02
https://github.com/Laravel-Backpack/PageManager/issues/2#issuecomment-225615723
Here you say

> Of course, you will need to have your page templates in resources/views/pages, with the same name you used in your PageTemplates functions.

How the template for "about_us" page must look like? Any special sections? What I must to put in the template to see the content I write in the "content"-field of the PageManager (/admin/page url)?

**Comment by tabacitu** [comment] 2017-01-10 07:20
@andreich1980 your views can look any way you want, nothing is mandatory there. You can try a ```dd($page);``` to see the them.

**Comment by andreich1980** [comment] 2017-01-10 07:31
Oh, I had to understand it from the PageController code. Thanks.

**Comment by GustavoBrowne** [comment] 2021-04-13 20:52
Hi,
I'm new to laravel page builder, I keep getting a DNS_PROBE_FINISHED_NXDOMAIN error when try to preview a template I've been working on. It's not the browser and I've already cleared the DNS cache can anyone assist with this issue

**Comment by promatik** [comment] 2021-04-21 23:12
Hi @GustavoBrowne `DNS_PROBE_FINISHED_NXDOMAIN` doesn't seem to be related with backpack, does that happen with only the pages from PageManager?

**Comment by GustavoBrowne** [comment] 2021-04-22 01:02
Yea only when I try to preview the project besides that everything else
works totally fine but I can't seem to figure this out any help would be
greatly appreciated.
