### ISSUE TITLE
[Bug] visibility: hidden ckeditor and Wysiwyg

### ISSUE THREAD

**Issue by suro11777** [Laravel-Backpack/PageManager#114] opened 2021-04-07 07:55 UTC
# Bug report

### What I did
I just installed batskpak, and silence there visiblity:hidden
??

### What I expected to happen
I installed it before backpack, but it was not there, everything worked, but now I installed it using docker, if it matters
??
![Screenshot_9](https://user-images.githubusercontent.com/29690567/113830899-1a7aa300-9798-11eb-919d-a3259a8d16f2.png)

### Backpack, Laravel, PHP, DB version
php 8, laravel 8, backpack 4.1 
When I run ```php artisan backpack:version``` the output is:
Zend Engine v4.0.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.3, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.34.0@81892ca110795a9c46c7e198cba7763bfd2af0bf

### BACKPACK VERSION:
4.1.41@44770347b918e42c052d0a138c24535b43e32472

**Comment by pxpm** [comment] 2021-04-08 12:27
Hello @suro11777 

It seems you using this package, so I moved your issue over here. 

The `ckeditor` and `images` come from the `template` definition in `PageTemplates.php`. 

Could you share your definition ? 

Best,
Pedro

**Comment by suro11777** [comment] 2021-04-08 14:47
![image](https://user-images.githubusercontent.com/29690567/114047559-d02e1a80-989a-11eb-9338-01d96bcfffc4.png)
But never mind, it doesn't work in other places either.

**Comment by pxpm** [comment] 2021-04-09 08:46
@suro11777 it seems fine. Are you overriding the `ckeditor` file in your resources folder ?

**Comment by suro11777** [comment] 2021-04-09 08:54
no, I haven't changed anything.
I use backpack  it in another project, without docker, but everything  works fine there, did everything the same

**Comment by pxpm** [comment] 2021-04-09 09:48
The only thing I can think of is probably in your docker you are pulling some JavaScript that hides the editor?

I know for sure that backpack works with docker, so I am also a bit lost here.

**Comment by tabacitu** [comment] 2021-04-14 04:23
@pxpm , @suro11777 - this is very weird indeed. No idea what might be causing this either, but I can also confirm that creditor is working on all my machines, and in our [online demo](https://demo.backpackforlaravel.com/admin/login), so I'm pretty sure the problem is limited to @suro11777 's project, machine or a particular server configuration.

I have an idea that might help us narrow down what's happening: 

**@suro11777 if you [install our demo project](https://backpackforlaravel.com/docs/4.1/demo) the same way you have this project, what happens? Does the `ckeditor` field work inside the Monsters CRUD or not?**

**Comment by suro11777** [comment] 2021-04-14 04:48
Good day. Thank you. I'll try and tell

**Comment by tabacitu** [comment] 2021-04-19 09:56
Just tried on yet another machine and it's working well - I'm pretty sure it's a machine / particular server configuration problem limited to @suro11777 .

I'll close this issue for now since I don't think it represents a bug in the software.

@suro11777 if you get this again let us know and we'll reopen it, no problem.

Cheers!

**Closed by tabacitu** 2021-04-19 09:56 UTC
Labels: can't reproduce
